### ISSUE TITLE
Process goes into background upon clicking a Menu button.

### ISSUE THREAD

**Issue by Ariannae** [dmillerw/MineMenu#6]
As the title indicates, when some of the menus that mods add are added to the Radial Menu and are clicked on, Minecraft appears to go into the background process, as opposed to the foreground. The mouse cursor appears in the center of the game screen, and the menu does not show up. However, the menu will appear when clicked on from a general keybind. This does not appear to happen with all menus, only a few.

Examples include:
The "Skills" Menu from Dynamic Sword Skills
The "Baubles" Menu from Baubles/Thaumcraft
The "Battlegear" Menu from Mine and Blade Battlegear 2
The menu from Tinkers' Construct

Examples that work include:
Menus from the Custom NPCs mod
The stats screen from GokiStats

**Comment by aetherknight** [comment]
I am able to reproduce this without any other mods installed (aside from Forge):

* Mac OS X 10.10.1
* Java 7 1.7.0_71
* Minecraft 1.7.10
* Forge 10.13.2.1230
* MineMenu 1.2.0.B44

### Steps to reproduce:

1. Add a keybinding to trigger "Toggle Fullscreen" and to "press" the key
2. use the keybinding from the radial menu. Instead of Minecraft going fullscreen, the cursor appears and no longer controls the user's view until I click in the game window. The keyboard still works normally while the cursor is not hidden.

### With a few other mods

* Opening MAtmos' menu (a liteloader mod) works fine from MineMenu

* Opening JourneyMap's full screen view works fine
* Opening Waila's config menu does not work.

**Comment by GirafiStudios** [comment]
Process will not go into the background anymore - although this problem is caused by how Mine Menu tries to open GUIs. The GUI-opening would need a rewrite at some point.
